### ISSUE TITLE
TypeError: Zora-next

### ISSUE THREAD

**Issue by bramscher** [bdougie/zora-next#6]
![Screen Shot 2022-04-27 at 1 52 10 PM](https://user-images.githubusercontent.com/7459837/165628980-5b8a660a-0dd9-4b52-a30a-67d42a287354.png)

cab@Craigs-Mac-Pro zora-next % npm run dev

> zora-next@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
wait  - compiling...
event - compiled client and server successfully in 5.6s (124 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 389 ms (143 modules)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 59 ms (144 modules)
error - TypeError: Only HTTP(S) protocols are supported
error - TypeError: Only HTTP(S) protocols are supported

Thanks for looking at this. The server launches but i get:
TypeError: Only HTTP(S) protocols are supported

I have tried trouble shooting but a bit of a rookie on this.

**Comment by bdougie** [comment]
Looks like there is a change in how fetch is support non HTTPs urls, i.e. localhost. I don't have a solution at the moment but looking into it. 

Can you confirm the version of node that you are using? @bramscher

**Comment by bramscher** [comment]
Thanks for looking into this..   v17.6.0. I also tried it on 16.14.2.

**Comment by jasonericdavis** [comment]
It looks like fetch is complaining becuase some of the urls returned from query are using the `ipfs` protocol.

**Comment by bdougie** [comment]
Ah that is it. This is on zora, they return stuff that is not consistent and we will need to catch those or skip rendering them. Love it when folks break the internet for others 🍕.

**Comment by bramscher** [comment]
are there other tools like zora to work with thegraph to query and return NFT data?  Thanks!

**Comment by mtfoley** [comment]
I wonder if we could follow some of the steps here to use an IPFS gateway such as ipfs.io: https://stackoverflow.com/questions/68357819/how-can-i-get-the-image-url-from-ipfs-info-in-react-js
(Disclaimer: never done it before)

**Comment by bdougie** [comment]
Because this is a tutorial, I think I would just filter out any "ipfs" links. Mainly because I don't cover this in the video. The alternative is creating another video with this solution. 

I don't think I will have the time to even test this until Sunday though. Just in case some one wants to clone and try before I get a chance.

**Comment by mtfoley** [comment]
@bdougie I put up a PR, hope that helps - see #7.  

@bramscher let me know if you want to try out my feature branch and have any questions.

cc @jasonericdavis

**Comment by bramscher** [comment]
> 

@mtfoley thanks that would be great!

**Comment by bdougie** [comment]
Checked it out, thanks for the contribution @mtfoley
